"""V-KIS canvas query: the drawing IS the query, as structure — never as a picture.

For V-KIS the operator redraws a clip from memory: labelled object boxes are
dragged onto a 16:9 canvas, given one of the OD palette colours, and marked
required or optional. The frontend therefore already knows every label, colour
and normalized bbox. Rendering that to a PNG and asking an encoder to read the
structure back would only lose it, so the canvas JSON stays the query and is used
two ways:

  1. structured match against the OD index (`object_layout` channel) — each drawn
     object is matched one-to-one with a real detection by Hungarian assignment,
     so two drawn people cannot both match the same detected person;
  2. short English sentences for the PE text encoder, generated by rule (0 ms, no
     hallucination) rather than by a VLM.

Those two channels are the whole canvas pipeline. Rendering the canvas to a
raster for PE-image search is deliberately not implemented: freehand icons sit
far outside the photo distribution PE was trained on, so it would add a noisy
channel to reason about for little recall.

Everything here is pure logic over plain dicts so the scoring can be unit-tested
without Elastic, Milvus or a browser.
"""
from __future__ import annotations

import math
from dataclasses import dataclass, field
from typing import Any, Literal

# The 16-colour palette the OD pipeline quantises instance colours into
# (`color_palette_version = aic16-lab-v1`). The UI must offer exactly these, and
# a free RGB pick has to be mapped to the nearest one before querying, otherwise
# the colour term can never match a stored `dominant_color`.
PALETTE_RGB: dict[str, tuple[int, int, int]] = {
    "black": (0, 0, 0),
    "white": (255, 255, 255),
    "gray": (128, 128, 128),
    "red": (220, 20, 20),
    "orange": (255, 140, 0),
    "yellow": (240, 220, 30),
    "green": (30, 160, 60),
    "blue": (30, 80, 220),
    "navy": (20, 30, 90),
    "purple": (130, 40, 160),
    "pink": (240, 130, 180),
    "brown": (120, 70, 30),
    "beige": (225, 200, 160),
    "cyan": (40, 200, 210),
    "maroon": (110, 20, 30),
    "olive": (110, 110, 30),
}

# Colour is only extracted for classes with a useful surface colour, so asking for
# "a red crowd" can never match: the UI greys the colour picker out for the rest.
COLOR_CLASSES = frozenset({
    "person", "car", "motorcycle", "bicycle", "bus", "truck", "van", "train",
    "airplane", "helicopter", "boat", "ambulance", "fire truck", "helmet",
    "backpack", "handbag", "bottle", "chair", "table", "cell phone", "laptop",
    "screen", "flag", "sign", "banner", "book", "document", "plate", "bowl",
})

# Canonical labels the detector was actually prompted with, after synonym mapping
# (BASE_VOCAB + GENRE_VOCAB through CANONICAL_MAP in the OD notebook). A label
# outside this list has no OD evidence at all and must be routed to PE text
# instead of silently returning nothing.
CANONICAL_LABELS: tuple[str, ...] = (
    "person", "crowd", "car", "motorcycle", "bicycle", "bus", "truck", "van",
    "train", "airplane", "helicopter", "boat", "ambulance", "fire truck",
    "traffic light", "sign", "license plate", "microphone", "camera",
    "cell phone", "laptop", "screen", "text region", "tv logo", "banner",
    "table", "chair", "backpack", "handbag", "bottle", "book", "document",
    "fire", "smoke", "flood", "traffic accident", "protest", "flag", "podium",
    "money", "weapon", "building", "market", "hospital", "factory",
    "farm field", "helmet", "racing jersey", "road", "finish line", "mountain",
    "medal", "water bottle", "lion dance costume", "dragon dance", "drum",
    "cymbal", "traditional costume", "firecracker", "stage", "temple",
    "festival decoration", "lantern", "classroom", "whiteboard", "blackboard",
    "desk", "pen", "school uniform", "computer", "food", "dish", "plate",
    "bowl", "pan", "pot", "stove", "cutting board", "knife", "vegetable",
    "meat", "fish", "fruit", "spice", "ingredient", "kitchen", "cooking oil",
    "rice", "noodle", "ao dai", "pagoda", "statue", "handicraft",
    "traditional musical instrument", "village", "festival", "rice field",
    "landscape", "river", "mountain", "old house", "sampan", "floating market",
    "coconut tree", "fishing net", "traditional house", "water buffalo",
    "bridge", "palm tree", "wetland", "sunset", "riverbank", "outdoor activity",
    "sport", "city street", "nature", "smile",
)

# Vietnamese labels for the icon palette; the query itself always uses the
# canonical English label the detector was prompted with.
VI_LABELS: dict[str, str] = {
    "person": "người", "crowd": "đám đông", "car": "ô tô", "motorcycle": "xe máy",
    "bicycle": "xe đạp", "bus": "xe buýt", "truck": "xe tải", "boat": "thuyền",
    "airplane": "máy bay", "helicopter": "trực thăng", "microphone": "micro",
    "camera": "máy quay", "cell phone": "điện thoại", "screen": "màn hình",
    "table": "bàn", "chair": "ghế", "bottle": "chai", "book": "sách",
    "document": "tài liệu", "sign": "biển hiệu", "flag": "lá cờ", "fire": "lửa",
    "smoke": "khói", "flood": "ngập lụt", "food": "đồ ăn", "knife": "dao",
    "plate": "đĩa", "bowl": "bát", "river": "sông", "building": "tòa nhà",
    "podium": "bục phát biểu", "stage": "sân khấu", "temple": "đền chùa",
    "ao dai": "áo dài", "rice field": "ruộng lúa", "banner": "băng rôn",
    "helmet": "mũ bảo hiểm", "drum": "trống", "money": "tiền", "medal": "huy chương",
}

Mode = Literal["rough", "precise"]

# Rough is the default because a V-KIS operator is redrawing from memory: which
# objects are present and roughly where they sit relative to each other survives
# recall far better than an exact box. Precise is for when they can still see the
# clip on the big screen and can place boxes faithfully.
MODE_WEIGHTS: dict[str, dict[str, float]] = {
    "rough": {"conf": 0.15, "center": 0.40, "size": 0.10, "aspect": 0.05, "iou": 0.10, "color": 0.20},
    "precise": {"conf": 0.10, "center": 0.25, "size": 0.20, "aspect": 0.10, "iou": 0.25, "color": 0.10},
}

# Below this a pair is not evidence of anything; the object counts as unmatched
# rather than being force-assigned to whatever detection was left over.
MIN_PAIR_SCORE = 0.12
# A missing required object should sink a frame without deleting it: the detector
# has a finite prompted vocabulary and does miss objects, so this stays a penalty.
MISSING_REQUIRED_MULTIPLIER = 0.35
# Same reasoning in reverse for "must not be present".
EXCLUDED_PRESENT_MULTIPLIER = 0.70
RELATION_BONUS = 0.15


@dataclass
class CanvasObject:
    """One object the operator dragged onto the canvas."""

    id: str
    label: str
    bbox: tuple[float, float, float, float]  # normalized x1, y1, x2, y2
    color: str | None = None
    required: bool = True

    @property
    def center(self) -> tuple[float, float]:
        x1, y1, x2, y2 = self.bbox
        return ((x1 + x2) / 2, (y1 + y2) / 2)

    @property
    def size(self) -> tuple[float, float]:
        x1, y1, x2, y2 = self.bbox
        return (max(0.0, x2 - x1), max(0.0, y2 - y1))

    @property
    def area(self) -> float:
        width, height = self.size
        return width * height


@dataclass
class CanvasQuery:
    objects: list[CanvasObject] = field(default_factory=list)
    exclude_labels: list[str] = field(default_factory=list)
    action_text: str = ""
    mode: Mode = "rough"
    # Rendered PNG of the whole drawing (icons + freehand strokes), base64 data
    # URL. Only present when the operator enables the raster channel.
    image: str | None = None

    @property
    def labels(self) -> list[str]:
        return list(dict.fromkeys(obj.label for obj in self.objects))


def _clamp01(value: float) -> float:
    return min(1.0, max(0.0, value))


def parse_canvas(payload: dict[str, Any]) -> CanvasQuery:
    """Build a validated CanvasQuery from the request body.

    Boxes are clamped into [0,1] and degenerate ones are dropped: a zero-area box
    would make every geometric term meaningless while still demanding a match.
    """
    objects: list[CanvasObject] = []
    for index, raw in enumerate(payload.get("objects") or []):
        label = str(raw.get("label") or "").strip().lower()
        if not label:
            continue
        box = [float(value) for value in (raw.get("bbox") or [0, 0, 0, 0])[:4]]
        if len(box) != 4:
            continue
        x1, x2 = sorted((_clamp01(box[0]), _clamp01(box[2])))
        y1, y2 = sorted((_clamp01(box[1]), _clamp01(box[3])))
        if (x2 - x1) < 0.01 or (y2 - y1) < 0.01:
            continue
        color = str(raw.get("color") or "").strip().lower() or None
        if color and (color not in PALETTE_RGB or label not in COLOR_CLASSES):
            # An unmatchable colour filter would silently reject every frame, so
            # the object keeps its position/label meaning and drops the colour.
            color = None
        objects.append(
            CanvasObject(
                id=str(raw.get("id") or f"q{index + 1}"),
                label=label,
                bbox=(x1, y1, x2, y2),
                color=color,
                required=bool(raw.get("required", True)),
            )
        )
    mode = str(payload.get("mode") or "rough").lower()
    return CanvasQuery(
        image=_clean_data_url(payload.get("image")),
        objects=objects,
        exclude_labels=[
            str(item).strip().lower()
            for item in (payload.get("exclude_labels") or [])
            if str(item).strip()
        ],
        action_text=str(payload.get("action_text") or "").strip()[:300],
        mode="precise" if mode == "precise" else "rough",
    )


def _clean_data_url(value: object) -> str | None:
    """Accept only an inline PNG/JPEG data URL for the raster channel.

    The string is forwarded to the Kaggle encoder, so anything that is not
    self-contained image bytes — an http(s) URL above all — is rejected here
    rather than letting the encoder fetch an arbitrary host.
    """
    text = str(value or "").strip()
    if not text:
        return None
    if not text.startswith(("data:image/png;base64,", "data:image/jpeg;base64,")):
        return None
    return text


def nearest_palette_color(rgb: tuple[int, int, int]) -> str:
    """Snap a free RGB pick to the OD palette (plain RGB distance is enough for
    16 well-separated anchors; the pipeline itself compares in CIE Lab)."""
    return min(
        PALETTE_RGB,
        key=lambda name: sum((a - b) ** 2 for a, b in zip(PALETTE_RGB[name], rgb)),
    )


# ---- spatial vocabulary -------------------------------------------------

def zone_of(cx: float, cy: float) -> str:
    """Nine-zone position name, matching the OD `position` field."""
    horizontal = "left" if cx < 1 / 3 else ("right" if cx > 2 / 3 else "center")
    vertical = "top" if cy < 1 / 3 else ("bottom" if cy > 2 / 3 else "middle")
    if horizontal == "center" and vertical == "middle":
        return "center"
    return f"{vertical}_{horizontal}"


def grid7_of(cx: float, cy: float) -> str:
    """Cell id in the 7×7 grid the OD documents are quantised into."""
    row = min(6, max(0, int(cy * 7)))
    col = min(6, max(0, int(cx * 7)))
    return f"r{row}c{col}"


_ZONE_PHRASES = {
    "top_left": "in the top left", "top_center": "at the top", "top_right": "in the top right",
    "middle_left": "on the left", "center": "in the center", "middle_right": "on the right",
    "bottom_left": "in the lower left", "bottom_center": "at the bottom",
    "bottom_right": "in the lower right",
}


def relation_between(a: CanvasObject, b: CanvasObject) -> str:
    """Relative spatial relation, the part of a redrawn layout that survives memory."""
    (ax, ay), (bx, by) = a.center, b.center
    ax1, ay1, ax2, ay2 = a.bbox
    bx1, by1, bx2, by2 = b.bbox
    if ax1 < bx2 and bx1 < ax2 and ay1 < by2 and by1 < ay2:
        return "overlapping"
    if abs(ax - bx) >= abs(ay - by):
        return "left_of" if ax < bx else "right_of"
    return "above" if ay < by else "below"


def canvas_relations(objects: list[CanvasObject]) -> list[dict[str, str]]:
    return [
        {"subject": a.id, "relation": relation_between(a, b), "object": b.id}
        for index, a in enumerate(objects)
        for b in objects[index + 1 :]
    ]


# ---- rule-based text queries for the PE encoder -------------------------

def describe_object(obj: CanvasObject, *, with_position: bool = True) -> str:
    parts = ["a"]
    if obj.color:
        parts.append(obj.color)
    parts.append(obj.label)
    text = " ".join(parts)
    if with_position:
        text = f"{text} {_ZONE_PHRASES[zone_of(*obj.center)]}"
    return text


def canvas_to_queries(canvas: CanvasQuery, *, max_objects: int = 5) -> list[str]:
    """Two or three short English sentences describing the canvas.

    Deliberately rule-based: it costs nothing, cannot hallucinate an object the
    operator never drew, and keeps colour/position/count that a VLM caption would
    blur. PE-G14 has a short text context, so the variants stay compact and are
    fused by max-cosine exactly like the existing query-expansion path.
    """
    if not canvas.objects:
        return [canvas.action_text] if canvas.action_text else []
    # Biggest first: the object dominating the drawing is the one the operator is
    # most sure about, and PE weights early tokens more.
    ranked = sorted(canvas.objects, key=lambda obj: -obj.area)[:max_objects]

    scene = ", ".join(describe_object(obj) for obj in ranked)
    layout = ", ".join(
        f"{obj.color + ' ' if obj.color else ''}{obj.label} {zone_of(*obj.center).replace('_', ' ')}"
        for obj in ranked
    )
    queries = [f"A video frame showing {scene}.", layout]
    if canvas.action_text:
        subjects = ", ".join(describe_object(obj, with_position=False) for obj in ranked[:3])
        queries.insert(0, f"{canvas.action_text}. {subjects}.")
    return list(dict.fromkeys(query for query in queries if query.strip()))


# ---- one-to-one assignment ----------------------------------------------

def _iou(a: tuple[float, float, float, float], b: tuple[float, float, float, float]) -> float:
    ix = min(a[2], b[2]) - max(a[0], b[0])
    iy = min(a[3], b[3]) - max(a[1], b[1])
    if ix <= 0 or iy <= 0:
        return 0.0
    intersection = ix * iy
    union = (a[2] - a[0]) * (a[3] - a[1]) + (b[2] - b[0]) * (b[3] - b[1]) - intersection
    return intersection / union if union > 0 else 0.0


def _detection_box(detection: dict[str, Any]) -> tuple[float, float, float, float]:
    box = detection.get("bbox_norm") or {}
    return (
        float(box.get("x1") or 0.0),
        float(box.get("y1") or 0.0),
        float(box.get("x2") or 0.0),
        float(box.get("y2") or 0.0),
    )


def pair_score(obj: CanvasObject, detection: dict[str, Any], weights: dict[str, float]) -> float:
    """How well one drawn object matches one real detection, in [0, 1].

    A label mismatch scores 0 — position never rescues the wrong class. Colour is
    scored, not filtered, and only when OD marked it reliable: an unreliable
    colour must not decide the match either way.
    """
    if str(detection.get("canonical_label") or "").lower() != obj.label:
        return 0.0
    box = _detection_box(detection)
    center = detection.get("center_norm") or {}
    dcx = float(center.get("x") or (box[0] + box[2]) / 2)
    dcy = float(center.get("y") or (box[1] + box[3]) / 2)
    ocx, ocy = obj.center

    # √2 is the longest possible distance inside the unit square.
    distance = math.hypot(dcx - ocx, dcy - ocy) / math.sqrt(2)
    center_score = 1.0 - min(1.0, distance)

    ow, oh = obj.size
    dw, dh = max(1e-6, box[2] - box[0]), max(1e-6, box[3] - box[1])
    size_score = min(ow * oh, dw * dh) / max(1e-9, max(ow * oh, dw * dh))
    o_aspect, d_aspect = ow / max(1e-6, oh), dw / max(1e-6, dh)
    aspect_score = min(o_aspect, d_aspect) / max(o_aspect, d_aspect)

    conf = float(detection.get("conf") or 0.0)
    iou_score = _iou(obj.bbox, box)

    if not obj.color:
        color_score = 0.5  # neutral: the operator did not claim a colour
    elif not detection.get("color_reliable"):
        color_score = 0.4
    elif str(detection.get("dominant_color") or "").lower() == obj.color:
        color_score = 1.0
    elif obj.color in {str(name).lower() for name in (detection.get("color_names") or [])}:
        color_score = 0.75
    else:
        color_score = 0.0

    return _clamp01(
        weights["conf"] * conf
        + weights["center"] * center_score
        + weights["size"] * size_score
        + weights["aspect"] * aspect_score
        + weights["iou"] * iou_score
        + weights["color"] * color_score
    )


def _hungarian(cost: list[list[float]]) -> list[int]:
    """Minimum-cost one-to-one assignment (Kuhn–Munkres with potentials, O(n²m)).

    Greedy "best detection per object" would let two drawn people collapse onto
    the same detected person and report a perfect layout match for a frame that
    contains one person. Rows are drawn objects, columns detections; returns
    `assignment[row] = column`.
    """
    n = len(cost)
    if n == 0:
        return []
    m = len(cost[0])
    if m == 0:
        return [-1] * n
    inf = float("inf")
    u = [0.0] * (n + 1)
    v = [0.0] * (m + 1)
    p = [0] * (m + 1)  # p[column] = row currently assigned to it
    way = [0] * (m + 1)
    for i in range(1, n + 1):
        p[0] = i
        j0 = 0
        minv = [inf] * (m + 1)
        used = [False] * (m + 1)
        while True:
            used[j0] = True
            i0, delta, j1 = p[j0], inf, 0
            for j in range(1, m + 1):
                if used[j]:
                    continue
                current = cost[i0 - 1][j - 1] - u[i0] - v[j]
                if current < minv[j]:
                    minv[j], way[j] = current, j0
                if minv[j] < delta:
                    delta, j1 = minv[j], j
            for j in range(m + 1):
                if used[j]:
                    u[p[j]] += delta
                    v[j] -= delta
                else:
                    minv[j] -= delta
            j0 = j1
            if p[j0] == 0:
                break
        while j0:
            j1 = way[j0]
            p[j0] = p[j1]
            j0 = j1
    assignment = [-1] * n
    for j in range(1, m + 1):
        if p[j]:
            assignment[p[j] - 1] = j - 1
    return assignment


def match_canvas(
    canvas: CanvasQuery,
    detections: list[dict[str, Any]],
    *,
    min_conf: float = 0.20,
) -> dict[str, Any]:
    """Score one frame against the canvas and explain the result.

    Returns the frame score in [0, 1] plus the per-object matches, which the UI
    draws over the keyframe so the operator sees *why* a frame came back instead
    of a bare number.
    """
    weights = MODE_WEIGHTS[canvas.mode]
    usable = [
        detection
        for detection in detections
        if float(detection.get("conf") or 0.0) >= min_conf and detection.get("bbox_norm")
    ]
    objects = canvas.objects
    if not objects:
        return {"score": 0.0, "matches": [], "missing": [], "coverage": 0.0, "excluded_hits": []}

    scores = [[pair_score(obj, detection, weights) for detection in usable] for obj in objects]
    # Pad so every row has a column to take when detections are scarce; the padded
    # columns score 0 and are dropped below.
    width = max(len(usable), len(objects))
    for row in scores:
        row.extend([0.0] * (width - len(row)))
    assignment = _hungarian([[1.0 - value for value in row] for row in scores])

    matches: list[dict[str, Any]] = []
    missing: list[str] = []
    total = 0.0
    matched_by_id: dict[str, dict[str, Any]] = {}
    for row, obj in enumerate(objects):
        column = assignment[row] if row < len(assignment) else -1
        score = scores[row][column] if 0 <= column < width else 0.0
        if column < 0 or column >= len(usable) or score < MIN_PAIR_SCORE:
            missing.append(obj.id)
            continue
        detection = usable[column]
        match = {
            "object_id": obj.id,
            "label": obj.label,
            "score": round(score, 4),
            "detection_label": detection.get("label"),
            "conf": round(float(detection.get("conf") or 0.0), 4),
            "bbox_norm": detection.get("bbox_norm"),
            "position": detection.get("position"),
            "dominant_color": detection.get("dominant_color"),
            "color_reliable": bool(detection.get("color_reliable")),
            "color_ok": (
                None if not obj.color
                else str(detection.get("dominant_color") or "").lower() == obj.color
            ),
        }
        matches.append(match)
        matched_by_id[obj.id] = match
        total += score

    base = total / len(objects)
    if any(obj.required and obj.id in missing for obj in objects):
        base *= MISSING_REQUIRED_MULTIPLIER

    # Relations are only credited when BOTH ends matched, so a bonus can never be
    # earned by objects the frame does not actually contain.
    satisfied = considered = 0
    for index, first in enumerate(objects):
        for second in objects[index + 1 :]:
            if first.id not in matched_by_id or second.id not in matched_by_id:
                continue
            considered += 1
            drawn = relation_between(first, second)
            found = relation_between(
                _object_from_match(first, matched_by_id[first.id]),
                _object_from_match(second, matched_by_id[second.id]),
            )
            satisfied += int(drawn == found)
    if considered:
        base *= 1.0 + RELATION_BONUS * (satisfied / considered)

    excluded_hits = sorted({
        str(detection.get("canonical_label") or "")
        for detection in usable
        if str(detection.get("canonical_label") or "") in set(canvas.exclude_labels)
        and float(detection.get("conf") or 0.0) >= 0.40
    })
    if excluded_hits:
        base *= EXCLUDED_PRESENT_MULTIPLIER

    return {
        "score": round(_clamp01(base), 6),
        "matches": matches,
        "missing": missing,
        "coverage": round(len(matches) / len(objects), 4),
        "relations_satisfied": satisfied,
        "relations_considered": considered,
        "excluded_hits": excluded_hits,
    }


def _object_from_match(obj: CanvasObject, match: dict[str, Any]) -> CanvasObject:
    """The matched detection, expressed as a CanvasObject so the same relation
    function compares drawn layout and detected layout."""
    box = match.get("bbox_norm") or {}
    return CanvasObject(
        id=obj.id,
        label=obj.label,
        bbox=(
            float(box.get("x1") or 0.0),
            float(box.get("y1") or 0.0),
            float(box.get("x2") or 0.0),
            float(box.get("y2") or 0.0),
        ),
    )


def palette_manifest() -> dict[str, Any]:
    """What the UI needs to build the icon/colour palette, straight from the
    values the OD run used — so the picker can never offer a label or colour the
    index cannot answer."""
    return {
        "colors": [
            {"name": name, "hex": "#%02x%02x%02x" % rgb} for name, rgb in PALETTE_RGB.items()
        ],
        "labels": [
            {
                "label": label,
                "label_vi": VI_LABELS.get(label),
                "colorable": label in COLOR_CLASSES,
            }
            for label in CANONICAL_LABELS
        ],
        "modes": ["rough", "precise"],
        "color_palette_version": "aic16-lab-v1",
    }
